# Generated by Django 4.1.3 on 2022-12-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_comments_comment_id_alter_orders_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productsbid',
            name='status',
            field=models.CharField(default='Waiting', max_length=10),
        ),
    ]
