# Generated by Django 4.1.3 on 2022-12-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_productsbid_quantity_productsorders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Waiting for sending', max_length=40),
        ),
    ]
