# Generated by Django 4.1.3 on 2022-12-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer_first_name',
            field=models.CharField(default='Anonymous', max_length=40),
        ),
        migrations.AddField(
            model_name='orders',
            name='customer_last_name',
            field=models.CharField(default='Anonymous', max_length=40),
        ),
        migrations.AddField(
            model_name='orders',
            name='customer_phone',
            field=models.CharField(default='Anonymous', max_length=40),
        ),
    ]
